# Generated by Django 4.1.1 on 2022-09-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counselor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[("student", "student"), ("counsellor", "counsellor")],
                max_length=100,
            ),
        ),
    ]
