# Generated by Django 4.1.1 on 2022-09-07 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("counselor", "0002_alter_userprofile_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="password",
        ),
    ]
