# Generated by Django 4.1.1 on 2022-09-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counselor", "0003_remove_userprofile_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="google_picture",
            field=models.TextField(blank=True, null=True),
        ),
    ]
