# Generated by Django 4.1.1 on 2022-09-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("counselor", "0006_remove_userprofile_email_userprofile_fullname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                (
                    "Comment_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="counselor.studentextendedprofile",
                    ),
                ),
                (
                    "commented_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="counselor.userprofile",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="counselor.comment",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_posted"],
            },
        ),
    ]
