# Generated by Django 4.1.1 on 2022-09-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("counselor", "0007_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="Comment_to",
            new_name="comment_to",
        ),
    ]
