# Generated by Django 4.1.1 on 2022-09-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counselor", "0009_frequestly_asked_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="Secret_Key",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(blank=True, max_length=500, null=True)),
                ("secret_key", models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
