# Generated by Django 4.1.1 on 2023-04-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counselor", "0010_secret_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["date_posted"]},
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.CharField(max_length=250),
        ),
    ]
