# Generated by Django 4.1.1 on 2023-04-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counselor", "0011_alter_comment_options_alter_comment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(max_length=250),
        ),
    ]
